[workspace]
resolver = "2"
members = [
    "crates/tinox",
    "crates/tinox-common",
    "crates/tinox-lexer",
    "crates/tinox-parser",
    "crates/tinox-typecheck",
    "crates/tinox-codegen",
    "crates/tinox-lsp",
]

[workspace.package]
version = "2.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Tino"]
repository = "https://github.com/subnix-work/tinox"

[workspace.dependencies]
parking_lot = "0.12"
unicode-ident = "0.3"
hashbrown = "0.15"
rayon = "1.10"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
ureq = "2"
flate2 = "1"
tar = "0.4"
zip = "2"
sha2 = "0.10"

[profile.release]
opt-level = 3
lto = true
